---
title: "Dylan Koproski's Website"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

# About me
### Academic experinece

Columbia Mailman School of Public Health (2023-Present), New York, NY

* Master of Science in Biostatistics Public Health Data Science	      			   

Hamilton College (2019-2023), Clinton, NY

* Major in Biology, Minor in Math, Minor in Anthropology
* GPA: 3.86/4.0 (Dean’s List, NESCAC All Academic, IRCA Scholar Athlete)
* Varsity rower (2019-2023)
* Captain of varsity rowing team (2022-2023)
* Graduated Cum Laude with departmental honors in Biology

 New Canaan High School (2015-2019), New Canaan, CT
 
* Member of National Honor Society (2018-2019)
* Varsity rower (2015-2019)
* Captain of varsity rowing team (2019)

### Relevant coursework 

Calculus I, Calculus II, Calculus III (Multivariable Calculus), Statistics I, Statistics II (Statistical Modeling and Applications), Linear Algebra, Introductory Biology, Bioinformatics, Developmental Genetics, Genes and Genomes, Health Care Systems, Scanning Electron Microscopy

### Research experience

Hamilton College Biology Department (January 2021 - May 2023)

* Investigation of the effects of lead toxicity on Drosophila melanogaster behavior
*	Funded by the Levitt Center during the Summer of 2021

Hamilton College Anthropology Department (June 2022 - July 2022)

* Analysis of faunal remains from settlements in Iron Age Tall Dhiban, Jordan
*	Funded by Hamilton College Summer Science

### Work experience

Morgan Stanley (December 2019 - January 2020, June 2020 - August 2020, July 2022 - August 2022)

*	Worked under a financial advisor as an intern to help with analysis and other tasks
