---
title: "Instacart Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
    source: embed
    navbar:
      - { title: "Home", href: "https://dkoproski.github.io/index.html", align: left }      
      - { title: "About", href: "https://dkoproski.github.io/about.html", align: left }
      - { icon: "ion-social-github", href: "https://github.com/dkoproski/", align: right }
      - { icon: "ion-android-mail", href: "dfk2117@cumc.columbia.edu", align: right }
      
---

```{r, include= FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")

df_plot_c = 
  instacart |> 
  filter(department != "missing",
         department != "other") |> 
  group_by(department) |> 
  summarize(total_orders = n()) |> 
  arrange(total_orders)

df_plot_c |> 
  mutate(text_label = str_c("Department:", department, "<br> Total Orders:", total_orders)) |> 
  plot_ly(x = ~department, y = ~total_orders,
          type = "scatter",
          mode = "markers",
          text = ~text_label,
          color = ~department) |> 
  layout(title = "Total Orders by Department",
         yaxis = list(title = "Number of Orders"),
         xaxis = list(title = "Department", tickangle = -45)) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df_plot_b = 
  instacart |> 
  filter(department != "missing",
         department != "other") |> 
  group_by(order_hour_of_day, department) |> 
  summarize(count = n()) 

df_plot_b |> 
  mutate(text_label = str_c("Hour:", order_hour_of_day, "Count:", count)) |> 
  plot_ly(x = ~department, y = ~count,
          type = "box",
          color = ~department,
          text = ~text_label) |> 
          layout(title = "Distribution of # of Orders by Hour per Department",
          yaxis = list(title = "# of Orders"),
          xaxis = list(title = "Department"))
```

### Chart C

```{r}
df_plot_a =
   instacart |> 
   filter(aisle_id == 1) |> 
   group_by(order_hour_of_day, product_name) |> 
   summarize(count = n()) |> 
   arrange(-count)

df_plot_a |> 
  mutate(text_label = str_c("Product:", product_name, "<br> Count:", count)) |> 
  plot_ly(x = ~order_hour_of_day, y = ~count, 
        type = "scatter", 
        mode = "markers",
        color = ~product_name, 
        text = ~text_label,
        alpha = 0.5) |> 
 layout(title = "Frequency of Products in Aisle 1 by Hour of the Day",
        legend = list(font = list(size = 8)))
```


